services:
  caddy:
    build:
      context: caddy/
      dockerfile: Dockerfile
    container_name: caddy
    ports:
      - 8280:80
      - 8443:443
    environment:
      - TARGET_HOST=httpbin
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin