services:
  caddy:
    build:
      context: caddy/
      dockerfile: Dockerfile
    container_name: caddy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/sites:/config/caddy/sites
